import type { Metadata } from "next";
import Script from "next/script";
import { fontSans } from "@/lib/font"
import "./globals.css";
import { DesktopHeader } from "@/components/Header/DesktopHeader";
import { LoadingProvider } from "@/context/LoadingContext";
import LoaderWrapper from "@/components/Loader/LoaderWrapper";
import RightStickyBar from "@/components/RightStickyBar/RightStickyBar";
import MobileStickyBar from "@/components/RightStickyBar/MobileStickyBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Meta Pixel */}
        <Script
          id="meta-pixel"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              !function(f,b,e,v,n,t,s)
              {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
              n.callMethod.apply(n,arguments):n.queue.push(arguments)};
              if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
              n.queue=[];t=b.createElement(e);t.async=!0;
              t.src=v;s=b.getElementsByTagName(e)[0];
              s.parentNode.insertBefore(t,s)}(window, document,'script',
              'https://connect.facebook.net/en_US/fbevents.js');
              fbq('init', '1560632058423880');
              fbq('track', 'PageView');
            `,
          }}
        />

        {/* Meta Pixel NoScript */}
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: "none" }}
            src="https://www.facebook.com/tr?id=1560632058423880&ev=PageView&noscript=1"
          />
        </noscript>
      </head>
      <body className={`${fontSans.variable} font-sans antialiased`}>
        <LoadingProvider>
          <LoaderWrapper>
              <DesktopHeader />
              {children}
              <RightStickyBar/>
              <MobileStickyBar/>
          </LoaderWrapper>
        </LoadingProvider>
      </body>
    </html>
  );
}
