import type { Metadata } from "next";
import { fontSans } from "@/lib/font"
import "./globals.css";
import { DesktopHeader } from "@/components/Header/DesktopHeader";
import { LoadingProvider } from "@/context/LoadingContext";
import LoaderWrapper from "@/components/Loader/LoaderWrapper";
import RightStickyBar from "@/components/RightStickyBar/RightStickyBar";
import MobileStickyBar from "@/components/RightStickyBar/MobileStickyBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} font-sans antialiased`}>
        <LoadingProvider>
          <LoaderWrapper>
              <DesktopHeader />
              {children}
              <RightStickyBar/>
              <MobileStickyBar/>
          </LoaderWrapper>
        </LoadingProvider>
      </body>
    </html>
  );
}
